#ifndef CALCULATOROPERATIONSLIB_GLOBAL_H
#define CALCULATOROPERATIONSLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCULATOROPERATIONSLIB_LIBRARY)
#  define CALCULATOROPERATIONSLIB_EXPORT Q_DECL_EXPORT
#else
#  define CALCULATOROPERATIONSLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCULATOROPERATIONSLIB_GLOBAL_H
